name: "sasha-jr-chat"

services:
  frontend:
    depends_on:
      - "backend"
    image: sasha-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start

  backend:
    image: sasha-backend
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    command: npm run dev

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=chat
    ports:
      - "1985:5432"
    volumes:
    - shared:/shared
    - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kuyancev1985@mail.ru
      PGADMIN_DEFAULT_PASSWORD: sashapgadmin4
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  shared:
  db-data: